import { Section } from './types';

export const questionnaireSections: Section[] = [
  {
    id: 'section1',
    title: 'Audience Discovery',
    description: 'Define who you most want to reach and understand their challenges.',
    questions: [
      {
        id: 'Q1_1',
        type: 'textarea',
        label: 'Who do you most want this podcast to reach?',
        placeholder: 'Describe your ideal listener...',
        required: true,
      },
      {
        id: 'Q1_2',
        type: 'textarea',
        label: 'What are the top 3 challenges or pain points your ideal listener faces regarding your area of expertise?',
        placeholder: '1. Challenge one\n2. Challenge two\n3. Challenge three',
        required: true,
      },
      {
        id: 'Q1_3',
        type: 'radio',
        label: 'What level of experience does your ideal listener have in your area of expertise?',
        options: ['Beginner', 'Intermediate', 'Advanced'],
        required: true,
      },
      {
        id: 'Q1_4',
        type: 'textarea',
        label: 'What motivates your ideal listener to seek out more information in your area of expertise?',
        placeholder: 'Examples: Improve personal goals, improve clients/coaching clients, make more money, etc.',
        helpText: 'List 3 motivations',
        required: true,
      },
      {
        id: 'Q1_5',
        type: 'textarea',
        label: 'Are there specific values, attitudes, or beliefs you want your audience to share?',
        placeholder: 'Examples: open to new science, entrepreneurial, patient-centered, evidence-based, etc.',
        helpText: 'List 3 values',
        required: true,
      },
      {
        id: 'Q1_6',
        type: 'textarea',
        label: 'What is the next step you hope listeners take? Please rank these in order of importance.',
        placeholder: '1. Most important action\n2. Second action\n3. Third action',
        helpText: 'Examples: Sign up for newsletter, purchase a course, become a client, etc.',
        required: true,
      },
    ],
  },
  {
    id: 'section2',
    title: 'Demographic Basics',
    description: 'Basic demographic information about your target audience.',
    questions: [
      {
        id: 'Q2_1',
        type: 'text',
        label: 'What is their age range?',
        placeholder: 'e.g., 25-45, 30-50',
        required: true,
      },
      {
        id: 'Q2_2',
        type: 'text',
        label: 'What is their gender?',
        placeholder: 'e.g., Primarily female, Mixed, Mostly male',
        required: true,
      },
      {
        id: 'Q2_3',
        type: 'text',
        label: 'Where are they located geographically?',
        placeholder: 'e.g., Urban US cities, Suburban North America, Global',
        helpText: 'Include urban/suburban/rural, region, country',
        required: true,
      },
      {
        id: 'Q2_4',
        type: 'text',
        label: 'What is their education level?',
        placeholder: 'e.g., College educated, Graduate degree, High school',
        required: true,
      },
      {
        id: 'Q2_5',
        type: 'text',
        label: 'What is their income bracket?',
        placeholder: 'e.g., $75K-$150K, Six figures, Upper middle class',
        required: true,
      },
    ],
  },
  {
    id: 'section3',
    title: 'Professional Life',
    description: 'Information about their career and work life.',
    questions: [
      {
        id: 'Q3_1',
        type: 'text',
        label: 'What industry do they work in?',
        placeholder: 'e.g., Technology, Healthcare, Finance, Creative',
        required: true,
      },
      {
        id: 'Q3_2',
        type: 'text',
        label: 'What is their job title/role?',
        placeholder: 'e.g., Marketing Manager, Software Engineer, Entrepreneur',
        required: true,
      },
      {
        id: 'Q3_3',
        type: 'radio',
        label: 'Are they a decision-maker at work?',
        options: ['Yes, they make key decisions', 'Sometimes, they have some influence', 'No, they follow direction'],
        required: true,
      },
      {
        id: 'Q3_4',
        type: 'textarea',
        label: 'What are their career aspirations?',
        placeholder: 'Describe their professional goals and ambitions...',
        required: true,
      },
    ],
  },
  {
    id: 'section4',
    title: 'Personal Life',
    description: 'Insights into their personal life and lifestyle.',
    questions: [
      {
        id: 'Q4_1',
        type: 'text',
        label: 'What is their relationship status?',
        placeholder: 'e.g., Married, Single, In a relationship',
        required: true,
      },
      {
        id: 'Q4_2',
        type: 'text',
        label: 'Do they have children? If so, how many and what ages?',
        placeholder: 'e.g., Yes, 2 children ages 5-10, No children',
        required: true,
      },
      {
        id: 'Q4_3',
        type: 'text',
        label: 'What type of home do they live in?',
        placeholder: 'e.g., Apartment in the city, Suburban house, Rural property',
        required: true,
      },
      {
        id: 'Q4_4',
        type: 'textarea',
        label: 'How do they spend their free time?',
        placeholder: 'Describe their leisure activities...',
        required: true,
      },
      {
        id: 'Q4_5',
        type: 'textarea',
        label: 'What are their hobbies and interests?',
        placeholder: 'List 3 hobbies or interests...',
        required: true,
      },
    ],
  },
  {
    id: 'section5',
    title: 'Media Consumption',
    description: 'How they consume content and media.',
    questions: [
      {
        id: 'Q5_1',
        type: 'textarea',
        label: 'When and where do they listen to podcasts?',
        placeholder: 'e.g., During commute, at the gym, while cooking...',
        required: true,
      },
      {
        id: 'Q5_2',
        type: 'textarea',
        label: 'What other podcasts do they enjoy?',
        placeholder: 'List similar podcasts they likely listen to...',
        required: true,
      },
      {
        id: 'Q5_3',
        type: 'textarea',
        label: 'What social media platforms do they use most?',
        placeholder: 'e.g., LinkedIn, Instagram, Twitter/X, TikTok',
        required: true,
      },
      {
        id: 'Q5_4',
        type: 'textarea',
        label: 'What type of content do they engage with online?',
        placeholder: 'e.g., Long-form articles, short videos, newsletters, etc.',
        required: true,
      },
    ],
  },
  {
    id: 'section6',
    title: 'Psychographics',
    description: 'Their values, beliefs, motivations, and mindset.',
    questions: [
      {
        id: 'Q6_1',
        type: 'textarea',
        label: 'What are their core values?',
        placeholder: 'What principles guide their decisions?',
        required: true,
      },
      {
        id: 'Q6_2',
        type: 'textarea',
        label: 'What problems keep them up at night?',
        placeholder: 'Their biggest worries and concerns...',
        required: true,
      },
      {
        id: 'Q6_3',
        type: 'textarea',
        label: 'What are their biggest goals?',
        placeholder: 'List 3 major goals they want to achieve...',
        required: true,
      },
      {
        id: 'Q6_4',
        type: 'textarea',
        label: 'What motivates them?',
        placeholder: 'List 3 things that drive them forward...',
        required: true,
      },
    ],
  },
  {
    id: 'section7',
    title: 'Relationship to Your Podcast',
    description: 'How they connect with your specific show.',
    questions: [
      {
        id: 'Q7_1',
        type: 'textarea',
        label: 'Why would they choose your podcast?',
        placeholder: 'What makes your show appealing to them?',
        required: true,
      },
      {
        id: 'Q7_2',
        type: 'textarea',
        label: 'What problem does your podcast solve for them?',
        placeholder: 'What need does your show fulfill?',
        required: true,
      },
      {
        id: 'Q7_3',
        type: 'textarea',
        label: 'What value do they get from your show?',
        placeholder: 'What do they walk away with after each episode?',
        required: true,
      },
      {
        id: 'Q7_4',
        type: 'textarea',
        label: 'When are they most likely to listen?',
        placeholder: 'e.g., Monday mornings, weekend workouts, evening commute',
        required: true,
      },
      {
        id: 'Q7_5',
        type: 'textarea',
        label: 'What action do you want them to take after listening?',
        placeholder: 'Examples: sign up for a course, book a consultation, join a newsletter, share with colleagues',
        required: true,
      },
    ],
  },
];

export const TOTAL_QUESTIONS = questionnaireSections.reduce(
  (acc, section) => acc + section.questions.length, 
  0
);
